-- ============================================================
-- GIAS / Edubase Test System
-- PostgreSQL Initialisation Script
-- ============================================================

-- ------------------------------------------------------------
-- Schemas
-- ------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS core;

-- ------------------------------------------------------------
-- Search Aggregate Table
-- ------------------------------------------------------------
CREATE TABLE core.search_aggregate (
    search_aggregate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    provider_id TEXT UNIQUE,    
    provider_name TEXT,
    la_estab TEXT,
    dfe_number TEXT,
    provider_type_name TEXT,
    provider_type_id BIGINT,
    provider_address TEXT,
    companies_house_number TEXT,
    uk_provider_reference_number TEXT,
    postcode TEXT,
    county TEXT,
    town TEXT,
    local_authority_name TEXT,
    group_id TEXT,
    group_uid TEXT,
    status_code INTEGER,
    academy_counts INTEGER,
    provider_category TEXT
);

-- ------------------------------------------------------------
-- Establishment Aggregate Table
-- ------------------------------------------------------------
CREATE TABLE core.establishment_aggregate
(
    establishment_aggregate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- identifiers
    urn TEXT NOT NULL UNIQUE,
    ukprn TEXT,

    -- basic details
    name TEXT NOT NULL,
    establishment_number TEXT,

    -- active status
    status_code INTEGER,
    status_date DATE,    

    -- classification
    establishment_type_name TEXT,
    education_phase_name TEXT,

    -- lifecycle
    opened_date DATE,
    closed_date DATE,

    -- group membership
    group_uid BIGINT,
    group_code TEXT,
    group_name TEXT,
    group_type_name TEXT,
    group_open_date DATE,

    -- address
    site_name TEXT,
    address_line_1 TEXT,
    address_line_2 TEXT,
    town TEXT,
    county TEXT,
    postcode TEXT,

    -- local authority
    local_authority_code INTEGER,
    local_authority_name TEXT,

    -- admissions
    statutory_low_age INTEGER,
    statutory_high_age INTEGER,

    -- characteristics
    gender TEXT,
    religious_character TEXT,

    -- inspection
    ofsted_inspection_date DATE,
    ofsted_report_url TEXT,

    -- leadership
    headteacher_identifier TEXT,
    headteacher_name TEXT,

    -- SEND
    sen_provision TEXT,

    -- contact
    website TEXT,
    telephone_number TEXT
);

-- ------------------------------------------------------------
-- Establishment Governor Aggregate Table
-- ------------------------------------------------------------
CREATE TABLE core.establishment_governor_aggregate
(
    establishment_governor_aggregate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    establishment_urn TEXT NOT NULL,

    governor_id TEXT NOT NULL,
    governor_name TEXT NOT NULL,

    start_date DATE
);

-- ------------------------------------------------------------
-- Group Aggregate Table
-- ------------------------------------------------------------
CREATE TABLE core.group_aggregate
(
    group_aggregate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- business identifiers
    group_id TEXT NOT NULL UNIQUE,
    group_uid BIGINT NOT NULL,
    ukprn TEXT,
    companies_house_number TEXT,

    -- details
    name TEXT NOT NULL,
    group_type_name TEXT,

    -- leadership
    headteacher_identifier TEXT,
    headteacher_name TEXT,

    -- characteristics
    religious_character TEXT,

    -- contact
    website TEXT,
    telephone_number TEXT,

    -- address
    site_name TEXT,
    address_line_1 TEXT,
    address_line_2 TEXT,
    town TEXT,
    county TEXT,
    postcode TEXT,

    -- status
    group_status_label TEXT,
    group_status_effective_date DATE
);

-- ------------------------------------------------------------
-- Group Member Aggregate Table
-- ------------------------------------------------------------
CREATE TABLE core.group_member_aggregate
(
    group_member_aggregate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    group_id TEXT NOT NULL,

    establishment_urn TEXT NOT NULL,
    establishment_name TEXT NOT NULL,

    start_date DATE,
    end_date DATE
);

-- ------------------------------------------------------------
-- Indexes
-- ------------------------------------------------------------

CREATE INDEX idx_establishment_aggregate_urn
    ON core.establishment_aggregate (urn);

CREATE INDEX idx_establishment_aggregate_group_uid
    ON core.establishment_aggregate (group_uid);

CREATE INDEX idx_establishment_governor_aggregate_urn
    ON core.establishment_governor_aggregate (establishment_urn);

CREATE INDEX idx_group_aggregate_group_id
    ON core.group_aggregate (group_id);

CREATE INDEX idx_group_aggregate_group_uid
    ON core.group_aggregate (group_uid);

CREATE INDEX idx_group_member_aggregate_group_id
    ON core.group_member_aggregate (group_id);

CREATE INDEX idx_group_member_aggregate_establishment_urn
    ON core.group_member_aggregate (establishment_urn);


CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX idx_search_provider_id 
    ON core.search_aggregate (provider_id);
CREATE INDEX idx_search_provider_name 
    ON core.search_aggregate (provider_name);
CREATE INDEX idx_search_provider_laestab 
    ON core.search_aggregate (la_estab);
CREATE INDEX idx_search_provider_dfe_number 
    ON core.search_aggregate (dfe_number);
CREATE INDEX idx_search_provider_companies_house_number 
    ON core.search_aggregate (companies_house_number);
CREATE INDEX idx_search_provider_ukprn 
    ON core.search_aggregate (uk_provider_reference_number);
CREATE INDEX idx_search_provider_postcode 
    ON core.search_aggregate (postcode);
CREATE INDEX idx_search_provider_county 
    ON core.search_aggregate (county);
CREATE INDEX idx_search_provider_town 
    ON core.search_aggregate (town);
CREATE INDEX idx_search_provider_local_authority_name 
    ON core.search_aggregate (local_authority_name);
CREATE INDEX idx_search_provider_group_uid 
    ON core.search_aggregate (group_uid);
CREATE INDEX idx_search_provider_name_trgm 
    ON core.search_aggregate USING gin (provider_name gin_trgm_ops);