-- ============================================================
-- GIAS / Edubase Test System
-- PostgreSQL Initialisation Script
-- ============================================================

-- ------------------------------------------------------------
-- Schemas
-- ------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS ref;
CREATE SCHEMA IF NOT EXISTS core;


-- ------------------------------------------------------------
-- Reference tables
-- ------------------------------------------------------------
CREATE TABLE ref.establishment_family (
    establishment_family_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE ref.establishment_type (
    establishment_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_family_id BIGINT NOT NULL,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    is_school BOOLEAN NOT NULL DEFAULT FALSE,
    is_group BOOLEAN NOT NULL DEFAULT FALSE,
    is_early_years BOOLEAN NOT NULL DEFAULT FALSE,
    is_further_education BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_establishment_type_family
        FOREIGN KEY (establishment_family_id)
        REFERENCES ref.establishment_family (establishment_family_id)
);

CREATE TABLE ref.establishment_status (
    establishment_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE ref.education_phase_group (
    education_phase_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
);

CREATE TABLE ref.education_phase (
    education_phase_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    education_phase_group_id BIGINT NOT NULL,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    CONSTRAINT fk_education_phase_group
        FOREIGN KEY (education_phase_group_id)
        REFERENCES ref.education_phase_group (education_phase_group_id)
);

CREATE TABLE ref.group_type (
    group_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
);

CREATE TABLE ref.role_type (
    role_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
);

CREATE TABLE ref.title (
    title_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE ref.reason_establishment_opened (
    reason_establishment_opened_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
);

CREATE TABLE ref.reason_establishment_closed (
    reason_establishment_closed_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
);

-- ------------------------------------------------------------
-- Core parent tables
-- ------------------------------------------------------------
CREATE TABLE core.establishment (
    establishment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    urn TEXT UNIQUE,
    uid TEXT UNIQUE,
    name TEXT NOT NULL,
    establishment_number TEXT,
    laestab TEXT,
    dfe_number TEXT,
    establishment_type_id BIGINT NOT NULL,
    establishment_status_id BIGINT NOT NULL,
    headteacher_role_assignment_id BIGINT,
    CONSTRAINT fk_establishment_type
        FOREIGN KEY (establishment_type_id)
        REFERENCES ref.establishment_type (establishment_type_id),
    CONSTRAINT fk_establishment_status
        FOREIGN KEY (establishment_status_id)
        REFERENCES ref.establishment_status (establishment_status_id)
);

CREATE TABLE core.group_record (
    group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE,
    name TEXT NOT NULL,
    group_type_id BIGINT NOT NULL,
    headteacher_role_assignment_id BIGINT,
    CONSTRAINT fk_group_record_group_type
        FOREIGN KEY (group_type_id)
        REFERENCES ref.group_type (group_type_id)
);

CREATE TABLE core.person (
    person_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_id BIGINT,
    given_name TEXT,
    family_name TEXT,
    display_name TEXT,
    CONSTRAINT fk_person_title
        FOREIGN KEY (title_id)
        REFERENCES ref.title (title_id)
);

CREATE TABLE core.role (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL,
    role_type_id BIGINT NOT NULL,
    CONSTRAINT fk_role_person
        FOREIGN KEY (person_id)
        REFERENCES core.person (person_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_role_role_type
        FOREIGN KEY (role_type_id)
        REFERENCES ref.role_type (role_type_id)
);

-- ------------------------------------------------------------
-- Relationship tables
-- ------------------------------------------------------------
CREATE TABLE core.role_assignment (
    role_assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    establishment_id BIGINT,
    group_id BIGINT,
    preferred_job_title TEXT,
    CONSTRAINT fk_role_assignment_role
        FOREIGN KEY (role_id)
        REFERENCES core.role (role_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_role_assignment_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_role_assignment_group
        FOREIGN KEY (group_id)
        REFERENCES core.group_record (group_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_role_assignment_scope
        CHECK (establishment_id IS NOT NULL OR group_id IS NOT NULL)
);

CREATE TABLE core.establishment_group_membership (
    establishment_group_membership_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    membership_category TEXT,
    membership_flag TEXT,
    start_date DATE,
    end_date DATE,
    CONSTRAINT fk_establishment_group_membership_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_establishment_group_membership_group
        FOREIGN KEY (group_id)
        REFERENCES core.group_record (group_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_establishment_group_membership_dates
        CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

CREATE TABLE core.group_group_membership (
    parent_group_id BIGINT NOT NULL,
    child_group_id BIGINT NOT NULL,
    PRIMARY KEY (parent_group_id, child_group_id),
    CONSTRAINT fk_group_group_membership_parent
        FOREIGN KEY (parent_group_id)
        REFERENCES core.group_record (group_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_group_group_membership_child
        FOREIGN KEY (child_group_id)
        REFERENCES core.group_record (group_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_group_group_membership_not_self
        CHECK (parent_group_id <> child_group_id)
);

-- ------------------------------------------------------------
-- Module tables
-- ------------------------------------------------------------
CREATE TABLE core.establishment_identifier (
    establishment_identifier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT NOT NULL,
    identifier_type TEXT NOT NULL,
    identifier_value TEXT NOT NULL,
    CONSTRAINT fk_establishment_identifier_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE,
    CONSTRAINT uq_establishment_identifier
        UNIQUE (establishment_id, identifier_type, identifier_value)
);

CREATE TABLE core.group_identifier (
    group_identifier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    identifier_type TEXT NOT NULL,
    identifier_value TEXT NOT NULL,
    CONSTRAINT fk_group_identifier_group
        FOREIGN KEY (group_id)
        REFERENCES core.group_record (group_id)
        ON DELETE CASCADE,
    CONSTRAINT uq_group_identifier
        UNIQUE (group_id, identifier_type, identifier_value)
);

CREATE TABLE core.contact (
    contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT,
    group_id BIGINT,
    website TEXT,
    telephone_number TEXT,
    CONSTRAINT fk_contact_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_contact_group
        FOREIGN KEY (group_id)
        REFERENCES core.group_record (group_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_contact_owner
        CHECK (establishment_id IS NOT NULL OR group_id IS NOT NULL)
);

CREATE TABLE core.establishment_provision (
    establishment_provision_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT NOT NULL UNIQUE,
    education_phase_id BIGINT,
    nursery_provision_id BIGINT,
    official_sixth_form_id BIGINT,
    further_education_type_id BIGINT,
    fsm INTEGER,
    percentage_fsm NUMERIC(5,2),
    CONSTRAINT fk_establishment_provision_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_establishment_provision_education_phase
        FOREIGN KEY (education_phase_id)
        REFERENCES ref.education_phase (education_phase_id),
    CONSTRAINT chk_establishment_provision_percentage_fsm
        CHECK (percentage_fsm IS NULL OR percentage_fsm BETWEEN 0 AND 100)
);

-- ------------------------------------------------------------
-- Lifecycle Tables
-- ------------------------------------------------------------
CREATE TABLE core.establishment_status_history (
    establishment_status_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT NOT NULL,
    old_status_id BIGINT,
    new_status_id BIGINT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_establishment_status_history_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_establishment_status_history_old_status
        FOREIGN KEY (old_status_id)
        REFERENCES ref.establishment_status (establishment_status_id),
    CONSTRAINT fk_establishment_status_history_new_status
        FOREIGN KEY (new_status_id)
        REFERENCES ref.establishment_status (establishment_status_id)
);

CREATE TABLE core.establishment_lifecycle_event (
    establishment_lifecycle_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT NOT NULL,
    event_type TEXT NOT NULL,
    opened_reason_id BIGINT,
    closed_reason_id BIGINT,
    event_date DATE NOT NULL,
    CONSTRAINT fk_establishment_lifecycle_event_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_establishment_lifecycle_event_opened_reason
        FOREIGN KEY (opened_reason_id)
        REFERENCES ref.reason_establishment_opened (reason_establishment_opened_id),
    CONSTRAINT fk_establishment_lifecycle_event_closed_reason
        FOREIGN KEY (closed_reason_id)
        REFERENCES ref.reason_establishment_closed (reason_establishment_closed_id)
);

-- ------------------------------------------------------------
-- Placeholder / Additional Module Tables
-- ------------------------------------------------------------
CREATE TABLE core.site (
    site_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT NOT NULL,
    name TEXT,
    address_line_1 TEXT,
    address_line_2 TEXT,
    town TEXT,
    county TEXT,
    postcode TEXT,
    CONSTRAINT fk_site_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE
);

CREATE TABLE core.establishment_authority (
    establishment_authority_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT NOT NULL,
    authority_code TEXT,
    authority_name TEXT,
    CONSTRAINT fk_establishment_authority_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE
);

CREATE TABLE core.establishment_admissions (
    establishment_admissions_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT NOT NULL UNIQUE,
    admissions_policy TEXT,
    statutory_low_age INTEGER,
    statutory_high_age INTEGER,
    CONSTRAINT fk_establishment_admissions_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE
);

CREATE TABLE core.establishment_boarding (
    establishment_boarding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT NOT NULL UNIQUE,
    boarding_provision TEXT,
    CONSTRAINT fk_establishment_boarding_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE
);

CREATE TABLE core.establishment_religion (
    establishment_religion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT,
    group_id BIGINT,
    religious_character TEXT,
    religious_ethos TEXT,
    CONSTRAINT fk_establishment_religion_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_establishment_religion_group
        FOREIGN KEY (group_id)
        REFERENCES core.group_record (group_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_establishment_religion_owner
        CHECK (establishment_id IS NOT NULL OR group_id IS NOT NULL)
);

CREATE TABLE core.establishment_inspection (
    establishment_inspection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT NOT NULL,
    inspection_body TEXT,
    inspection_date DATE,
    inspection_outcome TEXT,
    CONSTRAINT fk_establishment_inspection_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE
);

CREATE TABLE core.establishment_sen (
    establishment_sen_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT NOT NULL UNIQUE,
    has_sen_provision BOOLEAN,
    sen_provision TEXT,
    CONSTRAINT fk_establishment_sen_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE
);

CREATE TABLE core.establishment_sen_need (
    establishment_sen_need_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT NOT NULL,
    sen_need_type TEXT NOT NULL,
    CONSTRAINT fk_establishment_sen_need_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE
);

CREATE TABLE core.establishment_alternative_provision (
    establishment_alternative_provision_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT NOT NULL UNIQUE,
    alternative_provision_type TEXT,
    CONSTRAINT fk_establishment_alternative_provision_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE
);

CREATE TABLE core.establishment_proprietor (
    establishment_proprietor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT NOT NULL,
    proprietor_name TEXT,
    proprietor_type TEXT,
    CONSTRAINT fk_establishment_proprietor_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id)
        ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- Deffered Foreign Keys (MUST RUN AFTER ALL TABLES EXIST)
-- ------------------------------------------------------------
ALTER TABLE core.establishment
ADD CONSTRAINT fk_establishment_headteacher_role_assignment
FOREIGN KEY (headteacher_role_assignment_id)
REFERENCES core.role_assignment (role_assignment_id);

ALTER TABLE core.group_record
ADD CONSTRAINT fk_group_record_headteacher_role_assignment
FOREIGN KEY (headteacher_role_assignment_id)
REFERENCES core.role_assignment (role_assignment_id);

-- ------------------------------------------------------------
-- Indexes
-- ------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX idx_establishment_urn_trgm ON core.establishment USING gin (urn gin_trgm_ops);
CREATE INDEX idx_establishment_name_trgm ON core.establishment USING gin (name gin_trgm_ops);

CREATE INDEX idx_establishment_type_id ON core.establishment (establishment_type_id);
CREATE INDEX idx_establishment_status_id ON core.establishment (establishment_status_id);
CREATE INDEX idx_establishment_urn ON core.establishment (urn);
CREATE INDEX idx_establishment_laestab ON core.establishment (laestab);
CREATE INDEX idx_establishment_uid ON core.establishment (uid);
CREATE INDEX idx_group_record_group_type_id ON core.group_record (group_type_id);
CREATE INDEX idx_role_person_id ON core.role (person_id);
CREATE INDEX idx_role_role_type_id ON core.role (role_type_id);
CREATE INDEX idx_role_assignment_role_id ON core.role_assignment (role_id);
CREATE INDEX idx_role_assignment_establishment_id ON core.role_assignment (establishment_id);
CREATE INDEX idx_role_assignment_group_id ON core.role_assignment (group_id);
CREATE INDEX idx_establishment_identifier_establishment_id ON core.establishment_identifier (establishment_id);
CREATE INDEX idx_group_identifier_group_id ON core.group_identifier (group_id);
CREATE INDEX idx_contact_establishment_id ON core.contact (establishment_id);
CREATE INDEX idx_contact_group_id ON core.contact (group_id);
CREATE INDEX idx_establishment_group_membership_establishment_id ON core.establishment_group_membership (establishment_id);
CREATE INDEX idx_establishment_group_membership_group_id ON core.establishment_group_membership (group_id);
CREATE INDEX idx_group_group_membership_child_group_id ON core.group_group_membership (child_group_id);
CREATE INDEX idx_establishment_status_history_establishment_id ON core.establishment_status_history (establishment_id);
CREATE INDEX idx_establishment_lifecycle_event_establishment_id ON core.establishment_lifecycle_event (establishment_id);